---
name: PSScriptAnalyzer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  analyze:
    name: PSScriptAnalyzer
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code ⬇
        uses: actions/checkout@v3
      - name: Run PSScriptAnalyzer 🔎
        uses: microsoft/psscriptanalyzer-action@2044ae068e37d0161fa2127de04c19633882f061
        with:
          path: .\
          recurse: true 
          output: results.sarif
      - name: Upload results on Github
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif
